# Generated by Django 2.2.3 on 2019-07-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190705_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuser',
            name='is_rented',
        ),
        migrations.AddField(
            model_name='book',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
