# Generated by Django 2.2.3 on 2019-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190707_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_rented',
        ),
        migrations.AddField(
            model_name='bookuser',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
