# Generated by Django 2.2.3 on 2019-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190708_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'angielski'), ('pl', 'polski'), ('fr', 'francuzki'), ('es', 'hiszpański'), ('de', 'niemiecki')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Genre'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
    ]
