# Generated by Django 2.2.3 on 2019-07-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190710_1736'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Ausssthor',
        ),
    ]
