# Generated by Django 2.2.3 on 2019-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190710_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('pl', 'polish'), ('fr', 'french'), ('es', 'spanish'), ('de', 'german')], max_length=32, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Is rented'),
        ),
    ]
