# Generated by Django 2.2.3 on 2019-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190711_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
